version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    #command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=portainer.phoenyx.me
      - VIRTUAL_PORT=9000
    #ports:
      #- 8000:8000
      #- 9443:9443
    networks:
      - nginx_proxy_frontend
      - nginx_proxy_backend
      - agent_network
    #deploy:
    #  mode: replicated
    #  replicas: 1
    #  placement:
    #    constraints: [node.role == manager]


networks:
  agent_network:
    #external: true
  nginx_proxy_frontend:
    # add this if the network is already existing!
    external: true
  nginx_proxy_backend:
    # add this if the network is already existing!
    external: true

volumes:
   data:
