version: '3.9'

volumes:
  portainer-data:

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - type: bind
        source: /mnt/storage/portainer/data
        target: /data
      # - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      - 9443:9443
    networks:
      - nginx_proxy_frontend
      - nginx_proxy_backend

networks:
  nginx_proxy_frontend:
    # add this if the network is already existing!
    external: true
  nginx_proxy_backend:
    # add this if the network is already existing!
    external: true
