version: '3.9'

volumes:
  portainer-data:

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer.phoenyx.me
    restart: unless-stopped
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=portainer.phoenyx.me
      - VIRTUAL_PORT=9000
    # healthcheck:
    #   test: ['CMD', 'portainer', '--healthcheck']
    #   interval: 300s
    #   retries: 5
    #   timeout: 10s
    ports:
      - 8000:8000
    networks:
      - nginx_proxy_frontend
      - nginx_proxy_backend

networks:
  nginx_proxy_frontend:
    # add this if the network is already existing!
    external: true
  nginx_proxy_backend:
    # add this if the network is already existing!
    external: true
